apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 3
  selector: 
    app: vertex
  template:
    metadata:
      name: complexpod
      labels:
        app: vertex
    spec:
      containers:
         - name: myjava
           image: nginx
           ports: 
            - containerPort: 8080