apiVersion: v1
kind: Service
metadata:
  name: vertex-svc
  labels:
    app: vertex
    version: 2.6.1
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30002
     protocol: TCP
  selector:
    app: vertex
    version: 2.6.1